version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.TEST_MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.TEST_MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.TEST_MYSQL_ROOT }}
      MYSQL_PASSWORD: ${{ secrets.TEST_MYSQL_ROOT_PASSWORD }}
