name: CI Test 환경

on:
  push:

permissions:
  contents: read

jobs:
  Docker_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install docker-compose
    
      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
    
      - name: Run tests
        run: |
          # 테스트 관련 코드
    
      - name: Stop Docker Compose
        run: |
          docker-compose down